version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    depends_on:
      - mongodb
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: daraja_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      DARAKA_API_URL: https://sandbox.safaricom.co.ke/mpesa/b2c/v3/paymentrequest
      DARAKA_API_TOKEN_URL: https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
      DARAKA_API_CONSUMER_KEY: 0ppxGt4BfdATyGXFoFgaYmpybq6khOuQjE2J5n16vL6HcJ5G
      DARAKA_API_CONSUMER_SECRET: 4L8Zi44vIAtNGUaM6pVGe7sInrTxIU6b85rWOeSyqFZqMFPymBOLBfTEZvss69Vc
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
